### ISSUE TITLE
Hovering on SNS icons change the positioning of the footer

### ISSUE THREAD

**Issue by oladhari** [Kanata0204/gyakukyujin#4]
when hovering on the SNS icons (twitter, Facebook and Instagram ) on the bottom of the page, the footer positioning change which makes the UI interface so bad
please fix it
write a checklist on how you are going to proceed to fix this error

![Screenshot from 2020-03-09 19-25-34](https://user-images.githubusercontent.com/13581057/76296185-2841c880-62f9-11ea-904e-3d958cc91c3a.png)
![Screenshot from 2020-03-09 19-25-26](https://user-images.githubusercontent.com/13581057/76296187-2a0b8c00-62f9-11ea-9fc7-34e6d6b16c47.png)

**Comment by Kanata0204** [comment]
OK!

**Comment by Kanata0204** [comment]
Did This solve the issue?

**Comment by oladhari** [comment]
yes ! thank you
I closed the issue, thank you for your hard work!
