### ISSUE TITLE
Where to improve?

### ISSUE THREAD

**Issue by Kanata0204** [Kanata0204/gyakukyujin#7]
If you have any improvements or features you want, please give me your opinion!

**Comment by oladhari** [comment]
the contrast of the color is not accurate for example the SNS icons are barely seen with the background
could you change the color of the background or SNS icon to be more seen?

**Comment by Kanata0204** [comment]
That's true.
The icon under Contacts is quite hard to see.
Thanks for your advice!!

**Comment by oladhari** [comment]
> That's true.
> The icon under Contacts is quite hard to see.
> Thanks for your advice!!

Actually modern websites do not use too many colors, usually 3 main colors
always think about the eyes comfort for the user and readability of the content
next step we need to add a section for Portfolio, where you can link all the projects or applications that you have done, 
and as a developer the most important proof is Github 
here an example of my profile where green shows that I was active on GitHub and doing development works
![Screenshot from 2020-03-12 14-48-35](https://user-images.githubusercontent.com/13581057/76491247-98268f00-6470-11ea-9bf8-94b66da3c288.png)

so from now on any activity related to Programmation please try to do it on github :smile:

**Comment by Kanata0204** [comment]
Thank you for the long sentence.
Well, it's a great learning experience!!

**Comment by Kanata0204** [comment]
Please let me know if there are any other improvements!

**Comment by oladhari** [comment]
I remarked that the scaling is for all the button why not make it only for the SNS icon?
![Screenshot from 2020-03-12 22-56-15](https://user-images.githubusercontent.com/13581057/76577105-8cd27280-6507-11ea-9e37-62b413e80005.png)

**Comment by Kanata0204** [comment]
Because I felt that the design was good to have a personality.
But now I think it might be a little unnatural design.
I'd like to make only the icon bigger.
